// 3-vuejs/components/cell.vue
// nav.vue
<style>
</style>

<template>
  <div class="col-xs-1" v-on:click="handleClick">
    {{state}}
  </div>
</template>

<script>
var { CellStateEnum, CellFlagEnum } = require('minesweeper')
function cellState(cell) {
  if (cell.state === CellStateEnum.CLOSED) {
    if (cell.flag === CellFlagEnum.NONE) {
        return 'X'
    } else if (cell.flag === CellFlagEnum.EXCLAMATION) {
        return '!'
    } else if (cell.flag === CellFlagEnum.QUESTION) {
        return '?'
    }
  } else if (cell.state === CellStateEnum.OPEN) {
     if (cell.isMine) {
       return '*'
     } else {
       return cell.numAdjacentMines === 0 ?
         ' ' :
         cell.numAdjacentMines.toString()
     }
  }
}
export default {
  props: ["cell"],
  data() {
    return {
      state: cellState(this.cell)
    }
  },
  methods: {
    handleClick: function (e) {
      this.$dispatch('updated', this.cell.x, this.cell.y)
    }
  }
}
</script>

// 2-react/components/cell.js
var React = require('react')
var pin = require('linchpin')
var minesweeper = require('minesweeper')

// Enums
var CellStateEnum = minesweeper.CellStateEnum
var CellFlagEnum = minesweeper.CellFlagEnum

function cellState(cell) {
  if (cell.state === CellStateEnum.CLOSED) {
    if (cell.flag === CellFlagEnum.NONE) {
        return 'X'
    } else if (cell.flag === CellFlagEnum.EXCLAMATION) {
        return '!'
    } else if (cell.flag === CellFlagEnum.QUESTION) {
        return '?'
    }
  } else if (cell.state === CellStateEnum.OPEN) {
     if (cell.isMine) {
       return '*'
     } else {
       return cell.numAdjacentMines === 0 ?
         ' ' :
         cell.numAdjacentMines.toString()
     }
  }
}

module.exports = React.createClass({
    handleClick() {
      var cell = this.props.cell
      var board = this.props.board
      board.openCell(cell.x, cell.y)
      pin.emit('repaint')
    },
    render() {
      return  <div className="col-md-1" onClick={this.handleClick}>
            {  cellState(this.props.cell) }
        </div>
    }
})
